$main_monitor = 
source = ~/.cache/hypr/lock_monitor.conf
source = ~/.cache/wal/colors-hyprlock.conf

general {
    hide_cursor = true
}

# Fallback/Default Background: Black for all monitors
background {
    monitor =
    color = rgb(15, 15, 15)
}

# Active/Main Monitor Background: Blurred Wallpaper
background {
    monitor = $main_monitor
    path = ~/.cache/hyde/wall.blur
    blur_passes = 0
    blur_size = 0
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# Time (Clock)
label {
    monitor = $main_monitor
    text = cmd[update:1000] echo -e "$(env LC_ALL=en_US.UTF-8 date +"%I:%M %p")"
    color = $color3
    font_size = 94
    font_family = CaskaydiaCove Nerd Font Mono Bold
    position = 0, -100
    halign = center
    valign = top
}

# Date
label {
    monitor = $main_monitor
    text = cmd[update:1000] echo -e "$(env LC_ALL=en_US.UTF-8 date +"%A, %d %B")"
    color = $foreground
    font_size = 22
    font_family = CaskaydiaCove Nerd Font Mono
    position = 0, -260
    halign = center
    valign = top
}

# Greeting
label {
    monitor = $main_monitor
    text = cmd[update:3600000] echo "Hello, $USER"
    color = $foreground
    font_size = 20
    font_family = CaskaydiaCove Nerd Font Mono
    position = 0, -380
    halign = center
    valign = top
}

# Input Field (Password Box)
input-field {
    monitor = $main_monitor
    size = 260, 50
    outline_thickness = 1
    dots_size = 0.28
    dots_spacing = 0.15
    dots_center = true
    outer_color = rgba(255, 255, 255, 0.1)
    inner_color = rgba(255, 255, 255, 0.1)
    font_color = rgba(255, 255, 255, 0.8)
    check_color = rgba(255, 255, 255, 0.1)
    fail_color = rgba(255, 255, 255, 0.1)
    fade_on_empty = false
    placeholder_text = Use Me
    hide_input = false
    position = 0, -140
    halign = center
    valign = center
}
