
# █░█ █▀ █▀▀ █▀█   █▀█ █▀█ █▀▀ █▀▀ █▀
# █▄█ ▄█ ██▄ █▀▄   █▀▀ █▀▄ ██▄ █▀░ ▄█

# Set your personal hyprland configuration here
# For a sample file, please refer to https://github.com/prasanthrangan/hyprdots/blob/main/Configs/.config/hypr/userprefs.t2

decoration {
    shadow {
        enabled = false
        range = 18
        render_power = 4
        offset = 0 0
    }
}

input {
    kb_layout = us,ara
    kb_variant = ,thal_bksl
    kb_options = grp:alt_shift_toggle
    sensitivity = -0.5
    accel_profile = flat
    force_no_accel = 0
}

# --- Game Mouse Cursor Fixes ---
# Confine mouse pointer to game windows (forces mouse capture, essential for dual-monitor setups)
# windowrule = confine_pointer 1, match:class ^(steam_app_2399830)$
# windowrule = confine_pointer 1, match:title ^(ArkAscended)$
# windowrule = confine_pointer 1, match:class ^(steam_app_.*)$

# --- Keyring Fix ---
# Start gnome-keyring-daemon for managing credentials and secrets securely in Electron/VSCode applications
exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = amixer -c Generic_1 sset 'Front Mic Boost' 2 && amixer -c Generic_1 sset 'Capture' 63 && sleep 2 && pactl set-default-source effect_output.rnnoise

# Source pywal colors
source = ~/.cache/wal/colors-hyprland.conf

general {
    border_size = 0
}

decoration {
    rounding = 8
}

windowrule = opacity 0.80 0.80, match:class ^(antigravity)$

misc {
    vrr = 1
}

render {
    direct_scanout = false
}

animations {
    animation = workspaces, 1, 3, default, slide
}

# Wipe clipboard history on startup to prevent database bloat
exec-once = cliphist wipe

windowrule = opacity 0.70 0.70, match:class ^(zen)$
windowrule = border_size 0, match:class ^(zen)$









